### PR TITLE
CRYP-27: sequence diagram for view wallets and update add wallets

### PR DESCRIPTION
**Pull request by jason-gerard**
## Changes
- Update the add wallets SD to include BtcEdge and only return after processing steps have been completed
- Add new SD for viewing wallets

### CODE REVIEW

**Review by domsec — APPROVED** [review]
Would we also need to show the `show progress screen` in the add wallet sequence?

If not then everything looks good and this PR can be merged.

**Comment by jason-gerard** [comment]
> Would we also need to show the `show progress screen` in the add wallet sequence?
> 
> If not then everything looks good and this PR can be merged.

I think it makes sense to add, will update now.

**Review by domsec — APPROVED** [review]
One last thing...form error message(s) state

**Comment by jason-gerard** [comment]
> One last thing...form error message(s) state

SD should only really show one flow, it gets too complicated if start doing the error handling, espcially the stuff thats just on the frontend. If we want to show case the actual states of the application an activity / state diagram would be much better, we can create some of those for complex flows that contain a lot of conditional states like add wallet while also keeping our SDs clean and to the point.

**Comment by domsec** [comment]
> > One last thing...form error message(s) state
> 
> SD should only really show one flow, it gets too complicated if start doing the error handling, espcially the stuff thats just on the frontend. If we want to show case the actual states of the application an activity / state diagram would be much better, we can create some of those for complex flows that contain a lot of conditional states like add wallet while also keeping our SDs clean and to the point.

Sounds good.

**Pull request merged**
