### PR TITLE
CRYP-239: Fix the bottom navigation tab bar displaying on screens it should not

### PR DESCRIPTION
**Pull request by domsec**
JIRA: https://cryptify.atlassian.net/browse/CRYP-239

## Fix
- The bottom navigation tab bar displaying on screens it should not according to the UI mockups
- Also fixed an issue where dynamically removing the bottom navigation tab bar leaves behind a grey box on iOS devices

@jason-gerard Can you please test this on your emulator to ensure this bug is fixed as I'm only able to test this on an iOS device. Also would it be preferred to have the `useTabBarHook` function placed in a standalone file similar to `useCachedResources.tsx` in the `packages/client/hooks` directory?

### CODE REVIEW

**Review by jason-gerard — APPROVED** [review]
Yea if you can move it to a separate hooks file would be best. Ill test it out later today and leave another comment

**Comment by jason-gerard** [comment]
@domsec just tested it out on android and all looks good to go

**Review by narroarrow — APPROVED** [review]

**Review by alexbara2000 — APPROVED** [review]
Separating your concerns is a very good idea, looks good!

**Comment by domsec** [comment]
> @domsec just tested it out on android and all looks good to go

Perfect, i'll go ahead an create the separate hooks file tomorrow.

**Pull request merged**
