### PR TITLE
CRYP-100: Add app splash screen

### PR DESCRIPTION
**Pull request by jason-gerard**
JIRA: https://cryptify.atlassian.net/browse/CRYP-100

## Dev notes
There isn't a way to add text or style the splash screen with padding / margin on the side so the best way I found was to just export the image directly from figma, set the background to the same blue and use that as the splash. This will ensure the spacing is correct and on devices with different aspect ratios or with status bars the same blue will show.

### CODE REVIEW

**Review by domsec — COMMENTED** [review]
Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?

**Comment by jason-gerard** [comment]
> Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?

This is the same way as its done in the article, if you check the right most image he has the text and logo as a phonse screen sized image just with a transparent background, I guess we could do the transparent background too just not sure how to remove the blue in figma.
image

**Comment by domsec** [comment]
> > Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?
> 
> This is the same way as its done in the article, if you check the right most image he has the text and logo as a phonse screen sized image just with a transparent background, I guess we could do the transparent background too just not sure how to remove the blue in figma.

I see. Here is a svg and png file of the logo for you to try. Ideally we should use svg however if you can't get svg to work then png will suffice.

SVG: https://drive.google.com/file/d/1I1ZPESq5QZiCHb6EoHfZfsyvxlWM-Hu5/view?usp=sharing
PNG: https://drive.google.com/file/d/1w8JQFogDYSBzzbSXbIud3WoGMTANKusl/view?usp=sharing

**Comment by jason-gerard** [comment]
> > > Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?
> > 
> > 
> > This is the same way as its done in the article, if you check the right most image he has the text and logo as a phonse screen sized image just with a transparent background, I guess we could do the transparent background too just not sure how to remove the blue in figma.
> 
> I see. Here is a svg and png file of the logo for you to try. Ideally we should use svg however if you can't get svg to work then png will suffice.
> 
> SVG: https://drive.google.com/file/d/1I1ZPESq5QZiCHb6EoHfZfsyvxlWM-Hu5/view?usp=sharing PNG: https://drive.google.com/file/d/1w8JQFogDYSBzzbSXbIud3WoGMTANKusl/view?usp=sharing

It needs to be scaled up to 4x and also keep the width for whatever padding you want. If you just put a picture of the text it will span the width of the phone screen. It also doesnt work with svg because it uses the img component in the implementation.

**Comment by domsec** [comment]
> > > > Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?
> 
> > > 
> 
> > > 
> 
> > > This is the same way as its done in the article, if you check the right most image he has the text and logo as a phonse screen sized image just with a transparent background, I guess we could do the transparent background too just not sure how to remove the blue in figma.
> 
> > 
> 
> > I see. Here is a svg and png file of the logo for you to try. Ideally we should use svg however if you can't get svg to work then png will suffice.
> 
> > 
> 
> > SVG: https://drive.google.com/file/d/1I1ZPESq5QZiCHb6EoHfZfsyvxlWM-Hu5/view?usp=sharing PNG: https://drive.google.com/file/d/1w8JQFogDYSBzzbSXbIud3WoGMTANKusl/view?usp=sharing
> 
> 
> 
> It needs to be scaled up to 4x and also keep the width for whatever padding you want. If you just put a picture of the text it will span the width of the phone screen. It also doesnt work with svg because it uses the img component in the implementation.

Hmm that's rather annoying. So to clarify, even if we use a 4x image of the logo, the width of the image will still span the width of the phone screen? And this issue doesn't occur with the current implementation?

**Review by domsec — APPROVED** [review]

**Comment by jason-gerard** [comment]
> > > > > Is it possible to just export the logo as a svg/png similar to how it's done in the following link https://hackernoon.com/how-to-design-a-splash-screen-with-expo-and-react-native ?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > This is the same way as its done in the article, if you check the right most image he has the text and logo as a phonse screen sized image just with a transparent background, I guess we could do the transparent background too just not sure how to remove the blue in figma.
> > 
> > 
> > > 
> > 
> > 
> > > I see. Here is a svg and png file of the logo for you to try. Ideally we should use svg however if you can't get svg to work then png will suffice.
> > 
> > 
> > > 
> > 
> > 
> > > SVG: https://drive.google.com/file/d/1I1ZPESq5QZiCHb6EoHfZfsyvxlWM-Hu5/view?usp=sharing PNG: https://drive.google.com/file/d/1w8JQFogDYSBzzbSXbIud3WoGMTANKusl/view?usp=sharing
> > 
> > 
> > It needs to be scaled up to 4x and also keep the width for whatever padding you want. If you just put a picture of the text it will span the width of the phone screen. It also doesnt work with svg because it uses the img component in the implementation.
> 
> Hmm that's rather annoying. So to clarify, even if we use a 4x image of the logo, the width of the image will still span the width of the phone screen? And this issue doesn't occur with the current implementation?

Yep the span is still correct and no issue right now with the 4x. Without the 4x the text just isn't crisp and it becomes very blurry.

**Comment by domsec** [comment]
Cool. We definitely want to keep that all nice and crisp. So good for merge in that case.

**Pull request merged**
