### PR TITLE
CRYP-241: Refactor TransactionDetails to simplify layout component structure

### PR DESCRIPTION
**Pull request by domsec**
JIRA: https://cryptify.atlassian.net/browse/CRYP-241

## Changes
- Refactor the layout components (`VStack`, `HStack`, and `Box`) used to simplify how the Transaction Details screen (`TransactionDetails.tsx`) is built.
- Used composition to create separate `BitcoinTransactionDetails` and `EthereumTransactionDetails` components that pass their specific Other Details section information into the generic `TransactionDetails` component
- Simplified data layout structure to use the `SingleLineListItem` and `MultiLineListItem` components

### CODE REVIEW

**Review by jason-gerard — APPROVED** [review]
Does this still pass the system tests?

**Comment by domsec** [comment]
> Does this still pass the system tests?

I wasn't able to run those tests because I still don't have my emulator set up. Can you run them for me for this PR and I'll make sure I have it set up by the end of this sprint.

**Review by narroarrow — APPROVED** [review]
Nice

**Comment by jason-gerard** [comment]
> > Does this still pass the system tests?
> 
> I wasn't able to run those tests because I still don't have my emulator set up. Can you run them for me for this PR and I'll make sure I have it set up by the end of this sprint.

Tested them, all pass

**Comment by domsec** [comment]
> 

Perfect. Thanks again

**Pull request merged**
